

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
  autogoal:
    image: autogoal/autogoal:full_image  
    ports:
      - 5000:5000
    depends_on:
      - mongodb
    network_mode: "host"