

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./data_for_metalearning:/data/db
  autogoal:
    image: autogoal/autogoal:full_image 
    container_name: autogoal 
    ports:
      - 5000:5000
    depends_on:
      - mongodb
    network_mode: "host"
    volumes:
      - "./vendor/illiterate/illiterate:/usr/lib/python3/dist-packages/illiterate"
      - ".:/home/coder/autogoal"
      - "~/.ssh:/home/coder/.ssh"
      - "~/.gitconfig:/home/coder/.gitconfig"
    user: "1000:1000"

  autogoal-keras:
    container_name: autogoal-keras
    hostname: autogoal-keras
    image: autogoal/autogoal:keras
    ports:
      - 8505:8501
      - 8005:8000
    volumes:
      - "./vendor/illiterate/illiterate:/usr/lib/python3/dist-packages/illiterate"
      - ".:/home/coder/autogoal"
      - "~/.ssh:/home/coder/.ssh"
      - "~/.gitconfig:/home/coder/.gitconfig"
    user: "1000:1000"

  autogoal-nltk:
    container_name: autogoal-nltk
    hostname: autogoal-nltk
    image: autogoal/autogoal:nltk
    ports:
      - 8503:8501
      - 8003:8000
    volumes:
      - "./vendor/illiterate/illiterate:/usr/lib/python3/dist-packages/illiterate"
      - ".:/home/coder/autogoal"
      - "~/.ssh:/home/coder/.ssh"
      - "~/.gitconfig:/home/coder/.gitconfig"
    user: "1000:1000"

  autogoal-regex:
    container_name: autogoal-regex
    hostname: autogoal-regex
    image: autogoal/autogoal:regex
    ports:
      - 8507:8501
      - 8007:8000
    volumes:
      - "./vendor/illiterate/illiterate:/usr/lib/python3/dist-packages/illiterate"
      - ".:/home/coder/autogoal"
      - "~/.ssh:/home/coder/.ssh"
      - "~/.gitconfig:/home/coder/.gitconfig"
    user: "1000:1000"

  autogoal-sklearn:
    container_name: autogoal-sklearn
    hostname: autogoal-sklearn
    image: autogoal/autogoal:sklearn
    ports:
      - 8502:8501
      - 8002:8000
    volumes:
      - "./vendor/illiterate/illiterate:/usr/lib/python3/dist-packages/illiterate"
      - ".:/home/coder/autogoal"
      - "~/.ssh:/home/coder/.ssh"
      - "~/.gitconfig:/home/coder/.gitconfig"
    user: "1000:1000"

  autogoal-spacy:
    container_name: autogoal-spacy
    hostname: autogoal-spacy
    image: autogoal/autogoal:spacy
    ports:
      - 8506:8501
      - 8006:8000
    volumes:
      - "./vendor/illiterate/illiterate:/usr/lib/python3/dist-packages/illiterate"
      - ".:/home/coder/autogoal"
      - "~/.ssh:/home/coder/.ssh"
      - "~/.gitconfig:/home/coder/.gitconfig"
    user: "1000:1000"

  autogoal-streamlit:
    container_name: autogoal-streamlit
    hostname: autogoal-streamlit
    image: autogoal/autogoal:streamlit
    ports:
      - 8508:8501
      - 8008:8000
    volumes:
      - "./vendor/illiterate/illiterate:/usr/lib/python3/dist-packages/illiterate"
      - ".:/home/coder/autogoal"
      - "~/.ssh:/home/coder/.ssh"
      - "~/.gitconfig:/home/coder/.gitconfig"
    user: "1000:1000"

  autogoal-telegram:
    container_name: autogoal-telegram
    hostname: autogoal-telegram
    image: autogoal/autogoal:telegram
    ports:
      - 8509:8501
      - 8009:8000
    volumes:
      - "./vendor/illiterate/illiterate:/usr/lib/python3/dist-packages/illiterate"
      - ".:/home/coder/autogoal"
      - "~/.ssh:/home/coder/.ssh"
      - "~/.gitconfig:/home/coder/.gitconfig"
    user: "1000:1000"

  autogoal-transformers:
    container_name: autogoal-transformers
    hostname: autogoal-transformers
    image: autogoal/autogoal:transformers
    ports:
      - 8510:8501
      - 8010:8000
    volumes:
      - "./vendor/illiterate/illiterate:/usr/lib/python3/dist-packages/illiterate"
      - ".:/home/coder/autogoal"
      - "~/.ssh:/home/coder/.ssh"
      - "~/.gitconfig:/home/coder/.gitconfig"
    user: "1000:1000"

  autogoal-wikipedia:
    container_name: autogoal-wikipedia
    hostname: autogoal-wikipedia
    image: autogoal/autogoal:wikipedia
    ports:
      - 8511:8501
      - 8011:8000
    volumes:
      - "./vendor/illiterate/illiterate:/usr/lib/python3/dist-packages/illiterate"
      - ".:/home/coder/autogoal"
      - "~/.ssh:/home/coder/.ssh"
      - "~/.gitconfig:/home/coder/.gitconfig"
    user: "1000:1000"
    
  autogoal-full:
    container_name: autogoal-full
    hostname: autogoal-full
    image: autogoal/autogoal:all-contribs
    ports:
      - 8512:8501
      - 8012:8000
    volumes:
      - "./vendor/illiterate/illiterate:/usr/lib/python3/dist-packages/illiterate"
      - ".:/home/coder/autogoal"
      - "~/.ssh:/home/coder/.ssh"
      - "~/.gitconfig:/home/coder/.gitconfig"
    user: "1000:1000"

  
