name: Build and Push to Docker

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build base image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: autogoal/autogoal:core
          context: "."
          file: "dockerfiles/core/dockerfile"

      - name: Discover contribs and build main image
        run: |
          contribs="common remote $(cd autogoal-contrib/ && ls -d autogoal_* | grep -v 'autogoal_contrib' | sed 's/autogoal_//')"
          docker build . -t autogoal/autogoal:latest-full -f dockerfiles/development/dockerfile --build-arg extras="common $contribs remote" --no-cache
          docker push autogoal/autogoal:latest-full

      - name: Generate Docker images for each contrib
        run: |
          contribs="$(cd autogoal-contrib/ && ls -d autogoal_* | grep -v 'autogoal_contrib' | sed 's/autogoal_//')"
          for contrib in $contribs
          do
            docker build . -t autogoal/autogoal:$contrib -f dockerfiles/development/dockerfile --build-arg extras="common $contrib remote" --no-cache
            docker push autogoal/autogoal:$contrib
          done
      
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
