name: Test Contribs

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(toJson(github.event.commits), '[skip ci]') == false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Core Docker image
        run: make docker
      
      - name: Build Docker image
        run: bash ./scripts/generate_full_image.sh

      - name: Run tests in Docker container
        run: |
          docker run --name test-container -d autogoal/autogoal:all-contribs tail -f /dev/null
          docker exec test-container bash -c "black --check autogoal-contrib"
          docker exec test-container bash -c "make test-contrib"
